/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 building.gltf 
Author: tyapkin.art (https://sketchfab.com/tyapkin.art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modular-sci-fi-kit-for-ue5-free-7f0ef96d57f741438e9e7f348d382575
Title: Modular Sci-Fi Kit for UE5 (FREE)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/building.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.ZenUV_SciFI_Building_ZenTrimSheet_01_0.geometry}
            material={materials.ZenTrimSheet_01}
          />
          <mesh
            geometry={nodes.ZenUV_SciFI_Building_ZenTrimSheet_01_0_1.geometry}
            material={materials.ZenTrimSheet_01}
          />
          <mesh
            geometry={nodes.ZenUV_SciFI_Building_ZenTrimSheet_01_0_2.geometry}
            material={materials.ZenTrimSheet_01}
          />
          <mesh
            geometry={nodes.ZenUV_SciFI_Building_ZenTrimSheet_01_0_3.geometry}
            material={materials.ZenTrimSheet_01}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/building.gltf");
